name: Multi OS Jobs


on:
  push:
    branches: [ no-branch ]
  

jobs:
  multi-os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - run: date
    

  final-job:
    runs-on: ubuntu-latest
    needs: [multi-os]
    steps:
      - run: date
